export const supportSeed = [
  {
    programName: "임산부 엽산·철분제 지원",
    programCategory: "national" as const,
    regionType: "all" as const,
    regionCode: null,
    eligibilityWeekStart: 0,
    eligibilityWeekEnd: 45,
    description:
      "보건소를 통해 임신 시기에 맞춰 엽산제와 철분제를 지원받을 수 있습니다. 세부 지원 방식은 지역별로 다를 수 있습니다.",
    applicationMethod: "거주지 관할 보건소 문의 또는 방문 신청",
    sourceApiId: "mohw-prenatal-supplement",
    sourceUrl: "https://www.bokjiro.go.kr",
    status: "active" as const,
  },
  {
    programName: "임신·출산 진료비 지원",
    programCategory: "national" as const,
    regionType: "all" as const,
    regionCode: null,
    eligibilityWeekStart: 0,
    eligibilityWeekEnd: 45,
    description:
      "임신과 출산 관련 진료비를 국민행복카드 바우처로 지원하는 제도입니다. 임신 확인 후 신청할 수 있습니다.",
    applicationMethod: "카드사, 은행, 정부24 또는 복지로에서 신청",
    sourceApiId: "nhis-happy-card",
    sourceUrl: "https://www.bokjiro.go.kr",
    status: "active" as const,
  },
  {
    programName: "임산부 산전검사 지원",
    programCategory: "national" as const,
    regionType: "all" as const,
    regionCode: null,
    eligibilityWeekStart: 11,
    eligibilityWeekEnd: 20,
    description:
      "보건소 등록 임산부를 대상으로 일부 산전검사 비용이나 검사항목을 지원하는 사업입니다. 지역별 운영 범위가 다를 수 있습니다.",
    applicationMethod: "거주지 관할 보건소 임산부 등록 후 안내",
    sourceApiId: "boards-fetal-screening",
    sourceUrl: "https://www.bokjiro.go.kr",
    status: "active" as const,
  },
  {
    programName: "고위험 임산부 의료비 지원",
    programCategory: "national" as const,
    regionType: "all" as const,
    regionCode: null,
    eligibilityWeekStart: 20,
    eligibilityWeekEnd: 45,
    description:
      "고위험 임신 질환으로 입원 치료가 필요한 경우 의료비 일부를 지원하는 제도입니다. 질환과 소득 기준 등 세부 요건이 있습니다.",
    applicationMethod: "거주지 관할 보건소 문의 및 신청",
    sourceApiId: "mohw-high-risk-pregnancy",
    sourceUrl: "https://www.bokjiro.go.kr",
    status: "active" as const,
  },
  {
    programName: "산모·신생아 건강관리 지원",
    programCategory: "national" as const,
    regionType: "all" as const,
    regionCode: null,
    eligibilityWeekStart: 32,
    eligibilityWeekEnd: 45,
    description:
      "출산 전후 산모와 신생아 건강관리를 위한 서비스 바우처를 지원하는 제도입니다. 출산 예정일을 기준으로 미리 신청할 수 있습니다.",
    applicationMethod: "복지로 또는 관할 보건소에서 신청",
    sourceApiId: "mohw-postpartum-care",
    sourceUrl: "https://www.bokjiro.go.kr",
    status: "active" as const,
  },
];
